name: mangkat_admin
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  google_fonts: ^6.0.0
  google_maps_flutter: ^2.5.0
  intl: any
  pointer_interceptor: ^0.9.3+6

  # flutter_polyline_points: ^2.0.0 error on web https://github.com/Dammyololade/flutter_polyline_points/issues/78
  flutter_polyline_no_xmlhttperror:
        git:
            url: https://github.com/wendellavila/flutter_polyline_no_xmlhttperror
            ref: main
  flutter_animate: ^4.2.0+1
  scrollable_table_view: ^2.0.2
  flex_color_picker: ^3.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.0
  flutter_localizations:
    sdk: flutter
  firebase_storage: ^11.4.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  firebase_database: ^10.3.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/